---
# tasks file for cisco-bgp-base-routing

# Configure BGP base config
- import_tasks: bgp-base-config.yml
    
# Configure BGP neighbors on Core routers
- import_tasks: bgp-core-config.yml
  when: routing.network_level == "CORE"
  
# Configure BGP neighbors on Aggregation routers
- ansible.builtin.import_tasks: bgp-aggr-config.yml
  when: routing.network_level == "AGGR"
  
# Configure BGP neighbors on Edge routers
- ansible.builtin.import_tasks: bgp-edge-config.yml
  when: routing.network_level == "EDGE"
  
  
