---
# tasks file for cisco-bgp-base-routing

- name: Configure BGP base config
  ansible.builtin.include_tasks:
    file: bgp-base-config.yml
    
- name: Configure BGP neighbors on Core routers
  ansible.builtin.include_tasks:
    file: bgp-core-config.yml
  when: routing.network_level == "CORE"
  
- name: Configure BGP neighbors on Aggregation routers
  ansible.builtin.include_tasks:
    file: bgp-aggr-config.yml
  when: routing.network_level == "AGGR"
  
- name: Configure BGP neighbors on Edge routers
  ansible.builtin.include_tasks:
    file: bgp-edge-config.yml
  when: routing.network_level == "EDGE"
  
  
