interfaces:
  - intf: "Loopback0"
    descr: "Router ID"
    enabled: true
    ipv4: "10.255.0.11/32"
    
  - intf: "Ethernet0/0"
    descr: "CORE-2"
    enabled: true
    ipv4: "10.255.100.1/30"
    
  - intf: "Ethernet0/1"
    descr: "CORE-3"
    enabled: true
    ipv4: "10.255.100.5/30"
    
  - intf: "Ethernet0/2"
    descr: "CORE-6"
    enabled: true
    ipv4: "10.255.100.9/30"
    
  - intf: "Ethernet0/3"
    descr: "CORE-7"
    enabled: true
    ipv4: "10.255.100.13/30"
    
  - intf: "Ethernet1/1"
    descr: "AGGR-1"
    enabled: true
    ipv4: "10.255.100.17/30"
    
  - intf: "Ethernet1/0"
    descr: "AGGR-2"
    enabled: true
    ipv4: "10.255.100.21/30"
    
  - intf: "Ethernet1/2"
    descr: "AGGR-6"
    enabled: true
    ipv4: "10.255.100.25/30"    
    

routing:
  network_level: "CORE"
  router_id: "10.255.0.11"
    

  
