interfaces:
  - intf: "Loopback0"
    descr: "Router ID"
    enabled: true
    ipv4: "10.255.0.69/32"
    
  - intf: "Ethernet0/1"
    descr: "AGGR-3"
    enabled: true
    ipv4: "10.255.100.158/30"
    
  - intf: "Ethernet0/0"
    descr: "AGGR-4"
    enabled: true
    ipv4: "10.255.100.170/30"

  - intf: "Ethernet0/3"
    descr: "UPLINK-3"
    enabled: true
    ipv4: "10.255.200.97/30"
    
  - intf: "Ethernet0/2"
    descr: "PEER-3"
    enabled: true
    ipv4: "10.255.200.101/30"

  - intf: "Ethernet1/0"
    descr: "CLIENT-6"
    enabled: true
    ipv4: "10.255.200.105/30"
        
  - intf: "Ethernet1/1"
    descr: "CLIENT-7"
    enabled: true
    ipv4: "10.255.200.109/30"
    


  - intf: "Loopback1"
    descr: "eBGP public network"
    enabled: true
    ipv4: "100.100.9.1/24"   
        

routing:
  network_level: "EDGE"
  router_id: "10.255.0.69"
