interfaces:
  - intf: "Loopback0"
    descr: "Router ID"
    enabled: true
    ipv4: "10.255.0.63/32"
    
  - intf: "Ethernet1/2"
    descr: "AGGR-1"
    enabled: true
    ipv4: "10.255.100.130/30"
    
  - intf: "Ethernet0/2"
    descr: "AGGR-2"
    enabled: true
    ipv4: "10.255.100.150/30"
   
  - intf: "Ethernet0/1"
    descr: "PEER-1"
    enabled: true
    ipv4: "10.255.200.41/30"
    
  - intf: "Ethernet0/0"
    descr: "PEER-2"
    enabled: true
    ipv4: "10.255.200.45/30"
     
  - intf: "Ethernet2/0"
    descr: "CLIENT-4"
    enabled: true
    ipv4: "10.255.200.49/30"



  - intf: "Loopback1"
    descr: "eBGP public network"
    enabled: true
    ipv4: "100.100.3.1/24"
    

routing:
  network_level: "EDGE"
  router_id: "10.255.0.63"
  bgp_networks:
    - network: "100.100.3.0"
      mask: "255.255.255.0"
      
