interfaces:
  - intf: "Loopback0"
    descr: "Router ID"
    enabled: true
    ipv4: "10.255.0.61/32"
    
  - intf: "Ethernet0/0"
    descr: "AGGR-1"
    enabled: true
    ipv4: "10.255.100.122/30"
    
  - intf: "Ethernet0/1"
    descr: "AGGR-2"
    enabled: true
    ipv4: "10.255.100.142/30"
    
  - intf: "Ethernet0/2"
    descr: "UPLINK-1"
    enabled: true
    ipv4: "10.255.200.1/30"
    
  - intf: "Ethernet0/3"
    descr: "UPLINK-2"
    enabled: true
    ipv4: "10.255.200.5/30"
    
  - intf: "Ethernet1/0"
    descr: "CLIENT-1"
    enabled: true
    ipv4: "10.255.200.9/30"
    
  - intf: "Ethernet1/1"
    descr: "CLIENT-2"
    enabled: true
    ipv4: "10.255.200.13/30"


  - intf: "Loopback1"
    descr: "eBGP public network"
    enabled: true
    ipv4: "100.100.1.1/24"
    
    

routing:
  network_level: "EDGE"
  router_id: "10.255.0.61"
